### ISSUE TITLE
大佬,删除demo相关文件以及路由报错问题

### ISSUE THREAD

**Issue by sxlh0814** [buqiyuan/vue3-antdv-admin#159]
大佬,我在前端项目删除了demo页面文件以及相关的路由,然后项目报错了
node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^
Error: Debug Failure. False expression: parameter should have errors when reporting errors
    at getSignatureApplicabilityError (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:73305:19)
    at resolveCall (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:73701:27)
    at resolveCallExpression (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:74102:14)
    at resolveSignature (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:74506:18)
    at getResolvedSignature (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:74528:20)
    at checkCallExpression (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:74640:25)
    at checkExpressionWorker (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:77855:18)
    at checkExpression (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:77766:34)
    at checkAwaitExpression (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:76349:27)
    at checkExpressionWorker (/Users/lihao/Documents/work/jiuguiProject/data_admin/vue3-antdv-admin/node_modules/typescript/lib/typescript.js:77883:18)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by buqiyuan** [comment]
没复现，请问使用的是最新的代码吗

**Comment by sxlh0814** [comment]
> 没复现，请问使用的是最新的代码吗

使用的是网盘之前的那个版本,我更新版本试一下
